### ISSUE TITLE
Many (really many!) DeprecationWarnings using tensorflow

### ISSUE THREAD

**Issue by JeromeDesseaux** [lukeiwanski/tensorflow#212]
First of all : THANKS. Really. THANKS. I can now use my AMD graphic card with Tensorflow. 

But there is still something really annoying : On every execution, I got hundreds or thousands DeprecationWarning message such as : 
`/home/jerome/.local/lib/python3.5/site-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
`

Or, `/home/jerome/.local/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py:560: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
`

Those two are the main I guess. It makes my terminal completely unreadable. 

My system : 
- Ubuntu 16.04
- HEAD dev/amd_gpu build with SYSCL support
- Python 3.5.2
- tensorflow 1.6r0

Any idea how to solve this? 

And again : thanks. Really!

**Comment by DuncanMcBain** [comment]
Hi @JeromeDesseaux, thanks for your report. As it happens we have made very very few modifications to the Python code in TensorFlow, as most of our efforts are in the C++ code so that we can accelerate it to run on GPUs. However, that's not to say it's impossible! Do you know if this issue happens with upstream TensorFlow, or has happened with older versions of TensorFlow upstream?

**Comment by JeromeDesseaux** [comment]
I'm using the last HEAD version from branch dev/amd_gpu. I'm kinda new, so how can I checkout an upstream version? I'd be glad to do it for helping you.

EDIT : I installed official tensorflow 1.5 release (CPU). No error. 

How can I rollback dev/amd_gpu to r1.5 ?

**Comment by DuncanMcBain** [comment]
Hi @JeromeDesseaux, it's not really possible to roll back, you're best off using the newer stuff generally. What I will do probably later this week is have a look at where that warning is from and see how we differ from upstream, because (as I say) we don't really modify the Python side of things unless we really need to.

**Comment by DuncanMcBain** [comment]
Just an update to say that I was not able to investigate this issue this week, but that I haven't forgotten about it!

**Comment by JeromeDesseaux** [comment]
Thank you :)
